### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by viniciushsantana** [verisign/cling#10]
I'm unable to install cling using any of the recommended installation methods:

```
pip install cling
Collecting cling
  Downloading cling-2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ax9lhwl_/cling/setup.py", line 4, in <module>
        import cling
      File "/tmp/pip-build-ax9lhwl_/cling/cling/__init__.py", line 14, in <module>
        from cli import Cling
    ModuleNotFoundError: No module named 'cli'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ax9lhwl_/cling/
```
or

```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import cling
  File "/cling/cling/__init__.py", line 14, in <module>
    from cli import Cling
ModuleNotFoundError: No module named 'cli'
```

Am I doing something wrong?

Thanks!

**Comment by bdeschut** [comment]
I had the same exact issue when using python3. The same procedure using python2.X worked for me

**Comment by collinsullivanhub** [comment]
I am having the same issue. The cli module cannot be found

**Comment by bplociennik** [comment]
Any chance to resolve that issue?
